# Generated by Django 5.1.2 on 2024-10-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('address', models.TextField(max_length=2000)),
                ('summary', models.TextField(max_length=2000)),
                ('degree', models.CharField(max_length=200)),
                ('pg', models.CharField(max_length=200)),
                ('school', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=200)),
                ('skills', models.TextField(max_length=2000)),
                ('experice', models.TextField(max_length=2000)),
            ],
        ),
    ]
