# Generated by Django 5.1.2 on 2024-10-23 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='experice',
            new_name='experience',
        ),
    ]
